### ISSUE TITLE
Mobile warning is shown to Firefox desktop users

### ISSUE THREAD

**Issue by ChristianVogl** [v4nn4/glyphs-generator#1]
### Steps taken:

- Visit https://v4nn4.github.io/glyphs-generator/ with Firefox on a desktop device.

### Expected result:

- See the glyph generator demo.

### Actual result:

- A mobile warning is shown:
  > Please switch to a desktop device for full website functionality.

### Technical details:
The `Regular expressions for mobile detection` in [/main/docs/script.js#L177](https://github.com/v4nn4/glyphs-generator/blob/main/docs/script.js#L177) is incorrect. The part `|gecko\/|` does not only detect Firefox mobile but also Firefox on desktop devices. Here is an overview of current Firefox useragents:
https://www.whatismybrowser.com/guides/the-latest-user-agent/firefox

As an example: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0`

**Comment by v4nn4** [comment]
Thanks a lot for spotting this! I updated the script according to https://stackoverflow.com/questions/11381673/detecting-a-mobile-browser. It is fixed in https://github.com/v4nn4/glyphs-generator/commit/94305c70b8e8e64457c2de0b71aafa4f84c31b04.
